name: 02 - workflow Events

on: 
    #push:
    #pull_request:
    workflow_dispatch: # added for manual triggering
    

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "The workflow was triggered by a a(n) ${{github.event_name}} event."



