name: 04-using actions

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest 
        defaults:
          run:
            working-directory: 04-using-actions/react-app # default locations 
        steps:
            - name: checkout Code 
              uses: actions/checkout@v4 # codes usually will not checkout from the repo we have to add this to checkout
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: latest
            - name: Install Dependencies
              run: npm ci
              
            - name: Run Unit test
              run: npm run test
            
        
        # Checkout the code 
        #1.insta;; deps of our react application
        #2. Exceute automate tests
