name: 04-using actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest 
        steps:
            - name: checkout Code 
              uses: actions/checkout@v4 # codes usually will not checkout from the repo we have to add this to checkout
            - name: printing Folders
              run: ls
        
        # Checkout the code 
        #1.insta;; deps of our react application
        #2. Exceute automate tests
